const lang = {
  signIn: '登陆',
  signOut: '登出',
  username: '用户名',
  password: '密码',
  arrangeClass: '排课',
  startTime: '开始时间',
  endTime: '结束时间',
  teacher: '教师',
  title: '标题',
  save: '保存',
  close: '关闭',
  description: '简介',
  confirmChangeEvent: '该课程已经被老师接受，确认更改吗？',
  Mon: '星期一',
  Tue: '星期二',
  Wed: '星期三',
  Thu: '星期四',
  Fri: '星期五',
  Sat: '星期六',
  Sun: '星期天',
  repeat: '每周重复',
};
export default lang;
